[2023-01-01T22:15:58.675-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.string_remove_id_not_found manual__2023-01-02T01:06:12.069428+00:00 [queued]>
[2023-01-01T22:15:58.688-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.string_remove_id_not_found manual__2023-01-02T01:06:12.069428+00:00 [queued]>
[2023-01-01T22:15:58.688-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:15:58.689-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T22:15:58.689-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T22:15:58.711-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): string.string_remove_id_not_found> on 2023-01-02 01:06:12.069428+00:00
[2023-01-01T22:15:58.716-0300] {standard_task_runner.py:55} INFO - Started process 25886 to run task
[2023-01-01T22:15:58.718-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'string.string_remove_id_not_found', 'manual__2023-01-02T01:06:12.069428+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmphpfnmq3o']
[2023-01-01T22:15:58.720-0300] {standard_task_runner.py:83} INFO - Job 202: Subtask string.string_remove_id_not_found
[2023-01-01T22:15:58.796-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.string.string_remove_id_not_found manual__2023-01-02T01:06:12.069428+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T22:15:58.860-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=string.string_remove_id_not_found
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T01:06:12.069428+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T01:06:12.069428+00:00
[2023-01-01T22:15:58.861-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/string/remove_not_found.py", line 6, in remove_not_found
    interactions = pd.read_csv(file_path)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './files/string/interactions_uniprot_ids.csv'
[2023-01-01T22:15:58.873-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=get_interactions, task_id=string.string_remove_id_not_found, execution_date=20230102T010612, start_date=20230102T011558, end_date=20230102T011558
[2023-01-01T22:15:58.880-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 202 for task string.string_remove_id_not_found ([Errno 2] No such file or directory: './files/string/interactions_uniprot_ids.csv'; 25886)
[2023-01-01T22:15:58.891-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-01T22:15:58.915-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
