[2022-12-15T04:07:53.559-0300] {processor.py:153} INFO - Started process (PID=208606) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:07:53.559-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:07:53.560-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:07:53.559-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:07:53.561-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:07:53.560-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:07:53.561-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:07:53.579-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.023 seconds
[2022-12-15T04:08:24.301-0300] {processor.py:153} INFO - Started process (PID=208846) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:24.302-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:08:24.303-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:08:24.303-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:24.305-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:08:24.304-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:08:24.306-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:24.330-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.031 seconds
[2022-12-15T04:08:54.676-0300] {processor.py:153} INFO - Started process (PID=209162) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:54.677-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:08:54.677-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:08:54.677-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:54.679-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:08:54.678-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:08:54.679-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:08:54.701-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.027 seconds
[2022-12-15T04:09:24.807-0300] {processor.py:153} INFO - Started process (PID=209466) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:24.808-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:09:24.809-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:09:24.809-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:24.811-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:09:24.810-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:09:24.811-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:24.843-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.039 seconds
[2022-12-15T04:09:55.432-0300] {processor.py:153} INFO - Started process (PID=210061) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:55.433-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:09:55.433-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:09:55.433-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:55.436-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:09:55.434-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:09:55.436-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:09:55.462-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.033 seconds
[2022-12-15T04:10:26.084-0300] {processor.py:153} INFO - Started process (PID=210519) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:26.085-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:10:26.085-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:10:26.085-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:26.087-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:10:26.086-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:10:26.088-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:26.112-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.031 seconds
[2022-12-15T04:10:56.626-0300] {processor.py:153} INFO - Started process (PID=210999) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:56.627-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:10:56.628-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:10:56.628-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:56.629-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:10:56.629-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:10:56.630-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:10:56.652-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.029 seconds
[2022-12-15T04:11:26.885-0300] {processor.py:153} INFO - Started process (PID=211426) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:26.886-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:11:26.886-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:11:26.886-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:26.888-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:11:26.887-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:11:26.888-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:26.913-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.031 seconds
[2022-12-15T04:11:57.306-0300] {processor.py:153} INFO - Started process (PID=211819) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:57.307-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:11:57.308-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:11:57.307-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:57.310-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:11:57.309-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:11:57.310-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:11:57.334-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.032 seconds
[2022-12-15T04:12:27.518-0300] {processor.py:153} INFO - Started process (PID=212094) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:27.519-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:12:27.519-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:12:27.519-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:27.522-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:12:27.521-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:12:27.522-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:27.541-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.025 seconds
[2022-12-15T04:12:58.501-0300] {processor.py:153} INFO - Started process (PID=212377) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:58.509-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:12:58.510-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:12:58.510-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:58.512-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:12:58.511-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:12:58.513-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:12:58.540-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.043 seconds
[2022-12-15T04:13:29.189-0300] {processor.py:153} INFO - Started process (PID=212746) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:29.197-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:13:29.198-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:13:29.198-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:29.200-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:13:29.199-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:13:29.200-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:29.224-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.038 seconds
[2022-12-15T04:13:59.583-0300] {processor.py:153} INFO - Started process (PID=213202) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:59.592-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:13:59.592-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:13:59.592-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:59.594-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:13:59.593-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:13:59.595-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:13:59.624-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.045 seconds
[2022-12-15T04:14:30.620-0300] {processor.py:153} INFO - Started process (PID=213591) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:14:30.629-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:14:30.630-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:14:30.630-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:14:30.633-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:14:30.632-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:14:30.634-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:14:30.676-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.061 seconds
[2022-12-15T04:15:01.638-0300] {processor.py:153} INFO - Started process (PID=213885) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:01.646-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:15:01.647-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:15:01.646-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:01.648-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:15:01.648-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:15:01.649-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:01.670-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.034 seconds
[2022-12-15T04:15:31.905-0300] {processor.py:153} INFO - Started process (PID=214350) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:31.906-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:15:31.907-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:15:31.906-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:31.910-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:15:31.908-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:15:31.911-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:15:31.955-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.054 seconds
[2022-12-15T04:16:02.317-0300] {processor.py:153} INFO - Started process (PID=214741) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:02.326-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:16:02.327-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:16:02.327-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:02.330-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:16:02.329-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:16:02.330-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:02.357-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.043 seconds
[2022-12-15T04:16:32.461-0300] {processor.py:153} INFO - Started process (PID=215028) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:32.461-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:16:32.462-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:16:32.462-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:32.464-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:16:32.463-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:16:32.464-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:16:32.494-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.036 seconds
[2022-12-15T04:17:02.940-0300] {processor.py:153} INFO - Started process (PID=215317) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:02.941-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:17:02.942-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:17:02.942-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:02.944-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:17:02.943-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:17:02.944-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:02.973-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.035 seconds
[2022-12-15T04:17:33.243-0300] {processor.py:153} INFO - Started process (PID=215602) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:33.251-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:17:33.252-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:17:33.252-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:33.254-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:17:33.253-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:17:33.255-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:17:33.285-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.045 seconds
[2022-12-15T04:18:04.199-0300] {processor.py:153} INFO - Started process (PID=215893) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:04.200-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:18:04.200-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:18:04.200-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:04.201-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:18:04.201-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:18:04.202-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:04.220-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.022 seconds
[2022-12-15T04:18:35.030-0300] {processor.py:153} INFO - Started process (PID=216211) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:35.039-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:18:35.040-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:18:35.040-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:35.042-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:18:35.041-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:18:35.042-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:18:35.067-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.041 seconds
[2022-12-15T04:19:05.099-0300] {processor.py:153} INFO - Started process (PID=216598) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:05.100-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:19:05.101-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:19:05.101-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:05.102-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:19:05.102-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:19:05.103-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:05.123-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.026 seconds
[2022-12-15T04:19:35.549-0300] {processor.py:153} INFO - Started process (PID=216953) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:35.549-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:19:35.550-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:19:35.550-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:35.552-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:19:35.551-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:19:35.552-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:19:35.571-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.024 seconds
[2022-12-15T04:20:05.991-0300] {processor.py:153} INFO - Started process (PID=217282) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:05.999-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:20:06.000-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:20:06.000-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:06.003-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:20:06.001-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:20:06.003-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:06.028-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.040 seconds
[2022-12-15T04:20:36.997-0300] {processor.py:153} INFO - Started process (PID=217708) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:37.005-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:20:37.006-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:20:37.006-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:37.008-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:20:37.007-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:20:37.008-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:20:37.036-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.042 seconds
[2022-12-15T04:21:07.341-0300] {processor.py:153} INFO - Started process (PID=218033) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:07.350-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:21:07.350-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:21:07.350-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:07.352-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:21:07.351-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:21:07.352-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:07.376-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.037 seconds
[2022-12-15T04:21:37.890-0300] {processor.py:153} INFO - Started process (PID=218389) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:37.891-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:21:37.892-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:21:37.892-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:37.894-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:21:37.893-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:21:37.895-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:21:37.927-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.039 seconds
[2022-12-15T04:22:08.437-0300] {processor.py:153} INFO - Started process (PID=218707) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:08.445-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:22:08.446-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:22:08.446-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:08.448-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:22:08.447-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:22:08.448-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:08.471-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.036 seconds
[2022-12-15T04:22:38.956-0300] {processor.py:153} INFO - Started process (PID=218994) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:38.964-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:22:38.965-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:22:38.965-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:38.967-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:22:38.966-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:22:38.967-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:22:38.990-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.036 seconds
[2022-12-15T04:23:09.547-0300] {processor.py:153} INFO - Started process (PID=219282) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:09.555-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:23:09.556-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:23:09.556-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:09.557-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:23:09.557-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:23:09.558-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:09.579-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.036 seconds
[2022-12-15T04:23:40.017-0300] {processor.py:153} INFO - Started process (PID=219569) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:40.025-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:23:40.026-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:23:40.025-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:40.027-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:23:40.026-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:23:40.027-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:23:40.047-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.034 seconds
[2022-12-15T04:24:10.250-0300] {processor.py:153} INFO - Started process (PID=219856) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:10.258-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:24:10.258-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:24:10.258-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:10.260-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:24:10.259-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:24:10.260-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:10.282-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.034 seconds
[2022-12-15T04:24:40.799-0300] {processor.py:153} INFO - Started process (PID=220144) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:40.799-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:24:40.800-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:24:40.800-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:40.801-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:24:40.801-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:24:40.802-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:24:40.822-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.025 seconds
[2022-12-15T04:25:10.985-0300] {processor.py:153} INFO - Started process (PID=220436) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:10.993-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:25:10.994-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:25:10.994-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:10.995-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:25:10.994-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:25:10.995-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:11.016-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.033 seconds
[2022-12-15T04:25:41.434-0300] {processor.py:153} INFO - Started process (PID=220722) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:41.435-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:25:41.435-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:25:41.435-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:41.437-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:25:41.436-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:25:41.437-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:25:41.461-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.028 seconds
[2022-12-15T04:26:11.894-0300] {processor.py:153} INFO - Started process (PID=221017) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:11.903-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:26:11.904-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:26:11.904-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:11.906-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:26:11.905-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:26:11.906-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:11.925-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.032 seconds
[2022-12-15T04:26:42.734-0300] {processor.py:153} INFO - Started process (PID=221433) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:42.735-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:26:42.735-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:26:42.735-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:42.737-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:26:42.736-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:26:42.737-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:26:42.765-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.034 seconds
[2022-12-15T04:27:13.149-0300] {processor.py:153} INFO - Started process (PID=221723) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:13.157-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:27:13.158-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:27:13.158-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:13.160-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:27:13.159-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:27:13.160-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:13.184-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.037 seconds
[2022-12-15T04:27:43.596-0300] {processor.py:153} INFO - Started process (PID=222008) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:43.604-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:27:43.605-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:27:43.604-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:43.606-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:27:43.605-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:27:43.606-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:27:43.626-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.033 seconds
[2022-12-15T04:28:14.040-0300] {processor.py:153} INFO - Started process (PID=222296) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:14.048-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:28:14.049-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:28:14.049-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:14.050-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:28:14.049-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:28:14.050-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:14.073-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.035 seconds
[2022-12-15T04:28:44.422-0300] {processor.py:153} INFO - Started process (PID=222582) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:44.430-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:28:44.430-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:28:44.430-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:44.432-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:28:44.431-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:28:44.432-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:28:44.455-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.035 seconds
[2022-12-15T04:29:14.689-0300] {processor.py:153} INFO - Started process (PID=222961) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:14.690-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:29:14.690-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:29:14.690-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:14.692-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:29:14.692-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:29:14.693-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:14.712-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.025 seconds
[2022-12-15T04:29:45.356-0300] {processor.py:153} INFO - Started process (PID=223249) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:45.364-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:29:45.364-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:29:45.364-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:45.366-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:29:45.365-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:29:45.366-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:29:45.388-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.035 seconds
[2022-12-15T04:30:15.509-0300] {processor.py:153} INFO - Started process (PID=223534) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:15.518-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:30:15.518-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:30:15.518-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:15.520-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:30:15.519-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:30:15.520-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:15.544-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.037 seconds
[2022-12-15T04:30:45.870-0300] {processor.py:153} INFO - Started process (PID=223819) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:45.879-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:30:45.879-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:30:45.879-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:45.881-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:30:45.880-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:30:45.882-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:30:45.903-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.036 seconds
[2022-12-15T04:31:16.113-0300] {processor.py:153} INFO - Started process (PID=224110) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:16.121-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:31:16.122-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:31:16.122-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:16.124-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:31:16.123-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:31:16.124-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:16.149-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.038 seconds
[2022-12-15T04:31:46.432-0300] {processor.py:153} INFO - Started process (PID=224395) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:46.433-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:31:46.433-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:31:46.433-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:46.435-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:31:46.434-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:31:46.435-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:31:46.456-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.026 seconds
[2022-12-15T04:32:16.919-0300] {processor.py:153} INFO - Started process (PID=224735) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:16.919-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:32:16.920-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:32:16.920-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:16.921-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:32:16.921-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:32:16.922-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:16.945-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.029 seconds
[2022-12-15T04:32:47.768-0300] {processor.py:153} INFO - Started process (PID=225040) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:47.776-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:32:47.777-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:32:47.777-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:47.778-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:32:47.778-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:32:47.779-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:32:47.802-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.038 seconds
[2022-12-15T04:33:17.850-0300] {processor.py:153} INFO - Started process (PID=225395) to work on /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:33:17.858-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/characterization.py for tasks to queue
[2022-12-15T04:33:17.859-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:33:17.859-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:33:17.861-0300] {logging_mixin.py:137} INFO - [2022-12-15T04:33:17.860-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/characterization.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/characterization.py", line 15
    generate_fasta = PythonOperator(task_id='generate_fasta', python_callable=)
                                                                              ^
SyntaxError: invalid syntax
[2022-12-15T04:33:17.861-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/characterization.py
[2022-12-15T04:33:17.883-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/characterization.py took 0.035 seconds
