[2023-02-14T21:50:53.060-0300] {processor.py:153} INFO - Started process (PID=4782) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:50:53.060-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:50:53.060-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.060-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:50:53.272-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.271-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:50:53.272-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:50:53.287-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.229 seconds
[2023-02-14T21:51:23.318-0300] {processor.py:153} INFO - Started process (PID=4947) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:23.319-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:51:23.319-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:23.319-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:23.559-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:23.558-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:51:23.559-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:23.574-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.258 seconds
[2023-02-14T21:51:54.029-0300] {processor.py:153} INFO - Started process (PID=5053) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:54.038-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:51:54.039-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:54.038-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:54.374-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:54.373-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:51:54.374-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:51:54.395-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.368 seconds
[2023-02-14T21:52:25.029-0300] {processor.py:153} INFO - Started process (PID=5176) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:25.037-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:52:25.038-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:25.038-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:25.360-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:25.359-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:52:25.360-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:25.379-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.353 seconds
[2023-02-14T21:52:56.096-0300] {processor.py:153} INFO - Started process (PID=5282) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:56.104-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:52:56.105-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:56.105-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:56.423-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:56.422-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:52:56.423-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:52:56.441-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.348 seconds
[2023-02-14T21:53:22.776-0300] {processor.py:153} INFO - Started process (PID=5547) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:22.781-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:53:22.781-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:22.781-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:22.993-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:22.993-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:53:22.994-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:23.009-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.235 seconds
[2023-02-14T21:53:53.047-0300] {processor.py:153} INFO - Started process (PID=5640) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:53.048-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:53:53.049-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.049-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:53.337-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.337-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:53:53.338-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:53:53.356-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.312 seconds
[2023-02-14T21:54:23.431-0300] {processor.py:153} INFO - Started process (PID=5752) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:23.431-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:54:23.432-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:23.432-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:23.776-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:23.775-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:54:23.776-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:23.795-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.367 seconds
[2023-02-14T21:54:56.080-0300] {processor.py:153} INFO - Started process (PID=6083) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:56.080-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:54:56.081-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.081-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:56.292-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.291-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:54:56.292-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:54:56.306-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.228 seconds
[2023-02-14T21:55:26.403-0300] {processor.py:153} INFO - Started process (PID=6201) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:26.404-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:55:26.404-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:26.404-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:26.746-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:26.745-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:55:26.746-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:26.765-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.364 seconds
[2023-02-14T21:55:57.156-0300] {processor.py:153} INFO - Started process (PID=6310) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:57.157-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:55:57.157-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:57.157-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:57.563-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:57.563-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:55:57.564-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:55:57.589-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.435 seconds
[2023-02-14T21:56:27.892-0300] {processor.py:153} INFO - Started process (PID=6397) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:27.901-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:56:27.902-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:27.901-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:28.257-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:28.256-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:56:28.257-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:28.277-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.388 seconds
[2023-02-14T21:56:58.844-0300] {processor.py:153} INFO - Started process (PID=6498) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:58.853-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:56:58.854-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:58.854-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:59.206-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:59.205-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:56:59.207-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:56:59.232-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.390 seconds
[2023-02-14T21:57:29.964-0300] {processor.py:153} INFO - Started process (PID=6606) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:57:29.973-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:57:29.974-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:29.973-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:57:30.306-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:30.305-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:57:30.306-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:57:30.328-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.369 seconds
[2023-02-14T21:58:00.443-0300] {processor.py:153} INFO - Started process (PID=6713) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:00.452-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:58:00.452-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:00.452-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:00.758-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:00.757-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:58:00.758-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:00.788-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.347 seconds
[2023-02-14T21:58:31.066-0300] {processor.py:153} INFO - Started process (PID=6825) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:31.067-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:58:31.067-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.067-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:31.400-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.399-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:58:31.400-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:58:31.418-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.355 seconds
[2023-02-14T21:59:01.889-0300] {processor.py:153} INFO - Started process (PID=6920) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:01.898-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:59:01.899-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:01.899-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:02.218-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:02.217-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:59:02.218-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:02.236-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.350 seconds
[2023-02-14T21:59:32.865-0300] {processor.py:153} INFO - Started process (PID=7025) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:32.866-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T21:59:32.866-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:32.866-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:33.194-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:33.193-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T21:59:33.194-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T21:59:33.214-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.352 seconds
[2023-02-14T22:01:58.347-0300] {processor.py:153} INFO - Started process (PID=7374) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:01:58.348-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:01:58.348-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.348-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:01:58.560-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.560-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:01:58.560-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:01:58.574-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.229 seconds
[2023-02-14T22:02:29.473-0300] {processor.py:153} INFO - Started process (PID=7538) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:29.482-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:02:29.483-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:29.482-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:29.835-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:29.834-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:02:29.835-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:29.854-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.383 seconds
[2023-02-14T22:02:35.806-0300] {processor.py:153} INFO - Started process (PID=7759) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:35.806-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:02:35.807-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:35.807-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:36.016-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:36.016-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:02:36.016-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:02:36.032-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.228 seconds
[2023-02-14T22:03:06.948-0300] {processor.py:153} INFO - Started process (PID=7851) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:06.956-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:03:06.957-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:06.957-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:07.286-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:07.286-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:03:07.287-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:07.308-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.362 seconds
[2023-02-14T22:03:37.423-0300] {processor.py:153} INFO - Started process (PID=7958) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:37.424-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:03:37.424-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:37.424-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:37.746-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:37.746-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:03:37.747-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:03:37.765-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.345 seconds
[2023-02-14T22:04:08.207-0300] {processor.py:153} INFO - Started process (PID=8038) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:08.216-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:04:08.217-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:08.217-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:08.555-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:08.555-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:04:08.555-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:08.574-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.369 seconds
[2023-02-14T22:04:39.246-0300] {processor.py:153} INFO - Started process (PID=8130) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:39.255-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:04:39.256-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:39.255-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:39.588-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:39.587-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:04:39.588-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:04:39.609-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.366 seconds
[2023-02-14T22:05:10.308-0300] {processor.py:153} INFO - Started process (PID=8225) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:10.316-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:05:10.317-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:10.317-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:10.629-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:10.628-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:05:10.629-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:10.648-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.342 seconds
[2023-02-14T22:05:40.751-0300] {processor.py:153} INFO - Started process (PID=8319) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:40.760-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:05:40.761-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:40.760-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:41.104-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:41.103-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:05:41.104-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:05:41.123-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.375 seconds
[2023-02-14T22:06:11.169-0300] {processor.py:153} INFO - Started process (PID=8412) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:11.178-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:06:11.179-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:11.179-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:11.512-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:11.511-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:06:11.512-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:11.533-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.366 seconds
[2023-02-14T22:06:42.371-0300] {processor.py:153} INFO - Started process (PID=8535) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:42.379-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:06:42.380-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:42.380-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:42.732-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:42.731-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:06:42.732-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:06:42.751-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.382 seconds
[2023-02-14T22:07:16.682-0300] {processor.py:153} INFO - Started process (PID=8806) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:16.683-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:07:16.683-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:16.683-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:16.895-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:16.894-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:07:16.895-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:16.910-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.229 seconds
[2023-02-14T22:07:47.823-0300] {processor.py:153} INFO - Started process (PID=8899) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:47.832-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:07:47.833-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:47.833-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:48.174-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:48.173-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:07:48.174-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:07:48.193-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.371 seconds
[2023-02-14T22:08:18.287-0300] {processor.py:153} INFO - Started process (PID=8993) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:18.296-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:08:18.296-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:18.296-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:18.624-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:18.623-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:08:18.624-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:18.643-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.358 seconds
[2023-02-14T22:08:49.359-0300] {processor.py:153} INFO - Started process (PID=9084) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:49.367-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:08:49.368-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:49.367-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:49.704-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:49.703-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:08:49.704-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:08:49.725-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.369 seconds
[2023-02-14T22:09:20.232-0300] {processor.py:153} INFO - Started process (PID=9178) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:20.240-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:09:20.241-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:20.241-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:20.563-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:20.563-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:09:20.564-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:20.585-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.356 seconds
[2023-02-14T22:09:51.348-0300] {processor.py:153} INFO - Started process (PID=9270) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:51.357-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:09:51.358-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:51.358-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:51.680-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:51.679-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:09:51.680-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:09:51.699-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.354 seconds
[2023-02-14T22:10:21.760-0300] {processor.py:153} INFO - Started process (PID=9366) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:21.769-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:10:21.770-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:21.769-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:22.103-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:22.102-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:10:22.103-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:22.123-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.364 seconds
[2023-02-14T22:10:52.188-0300] {processor.py:153} INFO - Started process (PID=9487) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:52.196-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:10:52.197-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:52.197-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:52.542-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:52.541-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:10:52.542-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:10:52.562-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.377 seconds
[2023-02-14T22:11:22.925-0300] {processor.py:153} INFO - Started process (PID=9587) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:22.933-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:11:22.934-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:22.934-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:23.276-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:23.275-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:11:23.276-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:23.301-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.380 seconds
[2023-02-14T22:11:54.232-0300] {processor.py:153} INFO - Started process (PID=9696) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:54.241-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:11:54.242-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:54.242-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:54.588-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:54.588-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:11:54.589-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:11:54.608-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.377 seconds
[2023-02-14T22:12:24.879-0300] {processor.py:153} INFO - Started process (PID=9802) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:24.888-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:12:24.889-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:24.889-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:25.203-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:25.203-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:12:25.204-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:25.224-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.348 seconds
[2023-02-14T22:12:55.339-0300] {processor.py:153} INFO - Started process (PID=9902) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:55.348-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:12:55.349-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:55.349-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:55.763-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:55.763-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:12:55.764-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:12:55.783-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.446 seconds
[2023-02-14T22:13:25.878-0300] {processor.py:153} INFO - Started process (PID=10233) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:25.879-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:13:25.880-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:25.880-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:26.166-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:26.166-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:13:26.166-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:26.184-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.310 seconds
[2023-02-14T22:13:56.401-0300] {processor.py:153} INFO - Started process (PID=10329) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:56.402-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:13:56.402-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:56.402-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:56.719-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:56.718-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:13:56.719-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:13:56.749-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.351 seconds
[2023-02-14T22:14:27.153-0300] {processor.py:153} INFO - Started process (PID=10426) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:27.154-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:14:27.154-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:27.154-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:27.485-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:27.484-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:14:27.485-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:27.512-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.362 seconds
[2023-02-14T22:14:57.546-0300] {processor.py:153} INFO - Started process (PID=10518) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:57.547-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:14:57.547-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:57.547-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:57.878-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:57.877-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:14:57.878-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:14:57.904-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.361 seconds
[2023-02-14T22:15:28.457-0300] {processor.py:153} INFO - Started process (PID=10606) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:28.465-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:15:28.466-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:28.466-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:28.803-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:28.802-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:15:28.803-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:28.821-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.367 seconds
[2023-02-14T22:15:58.892-0300] {processor.py:153} INFO - Started process (PID=10699) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:58.893-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:15:58.893-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:58.893-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:59.221-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:59.220-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:15:59.221-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:15:59.240-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.350 seconds
[2023-02-14T22:16:29.521-0300] {processor.py:153} INFO - Started process (PID=10791) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:16:29.530-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:16:29.530-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:29.530-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:16:29.860-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:29.859-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:16:29.860-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:16:29.881-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.362 seconds
[2023-02-14T22:17:00.367-0300] {processor.py:153} INFO - Started process (PID=10883) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:00.375-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:17:00.376-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:00.376-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:00.696-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:00.695-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:17:00.696-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:00.716-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.352 seconds
[2023-02-14T22:17:30.962-0300] {processor.py:153} INFO - Started process (PID=10986) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:30.971-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:17:30.972-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:30.971-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:31.308-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:31.308-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:17:31.309-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:17:31.330-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.370 seconds
[2023-02-14T22:18:02.001-0300] {processor.py:153} INFO - Started process (PID=11079) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:02.009-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:18:02.010-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:02.010-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:02.356-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:02.355-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:18:02.356-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:02.375-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.377 seconds
[2023-02-14T22:18:33.110-0300] {processor.py:153} INFO - Started process (PID=11172) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:33.118-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:18:33.119-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.119-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:33.446-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.445-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:18:33.446-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:18:33.467-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.359 seconds
[2023-02-14T22:19:03.525-0300] {processor.py:153} INFO - Started process (PID=11265) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:03.533-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:19:03.534-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:03.534-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:03.872-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:03.871-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:19:03.872-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:03.892-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.369 seconds
[2023-02-14T22:19:34.334-0300] {processor.py:153} INFO - Started process (PID=11357) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:34.343-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:19:34.344-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:34.344-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:34.671-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:34.670-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:19:34.671-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:19:34.691-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.359 seconds
[2023-02-14T22:24:15.935-0300] {processor.py:153} INFO - Started process (PID=11728) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:15.936-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:24:15.936-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:15.936-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:16.209-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:16.208-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:16.209-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:16.229-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.295 seconds
[2023-02-14T22:24:46.333-0300] {processor.py:153} INFO - Started process (PID=11885) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:46.334-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:24:46.334-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:46.334-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:46.588-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:46.587-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:46.588-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:46.607-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.279 seconds
[2023-02-14T22:24:57.262-0300] {processor.py:153} INFO - Started process (PID=12140) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:57.264-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:24:57.265-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:57.265-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:57.471-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:57.470-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:24:57.471-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:24:57.486-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.226 seconds
[2023-02-14T22:26:10.510-0300] {processor.py:153} INFO - Started process (PID=12455) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:26:10.512-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:26:10.512-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:10.512-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:26:10.776-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:10.775-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:26:10.776-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:26:10.790-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.281 seconds
[2023-02-14T22:27:31.120-0300] {processor.py:153} INFO - Started process (PID=12824) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:27:31.120-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:27:31.121-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.121-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:27:31.368-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.368-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:27:31.369-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:27:31.385-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.267 seconds
[2023-02-14T22:28:01.467-0300] {processor.py:153} INFO - Started process (PID=12930) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:01.477-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:28:01.478-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:01.478-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:01.899-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:01.898-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:01.899-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:01.918-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.456 seconds
[2023-02-14T22:28:10.459-0300] {processor.py:153} INFO - Started process (PID=13192) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:10.467-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:28:10.468-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:10.468-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:10.686-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:10.685-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:10.686-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:10.700-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.243 seconds
[2023-02-14T22:28:40.785-0300] {processor.py:153} INFO - Started process (PID=13292) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:40.794-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:28:40.795-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:40.794-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:41.139-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:41.138-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:28:41.139-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:28:41.158-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.375 seconds
[2023-02-14T22:29:11.210-0300] {processor.py:153} INFO - Started process (PID=13387) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:11.218-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:29:11.219-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:11.219-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:11.570-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:11.570-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:29:11.570-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:11.590-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.383 seconds
[2023-02-14T22:29:42.255-0300] {processor.py:153} INFO - Started process (PID=13496) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:42.256-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:29:42.258-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:42.257-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:42.581-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:42.580-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:29:42.581-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:29:42.596-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.347 seconds
[2023-02-14T22:30:06.765-0300] {processor.py:153} INFO - Started process (PID=13772) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:06.766-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:30:06.771-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:06.771-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:06.982-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:06.982-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:30:06.982-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:06.998-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.234 seconds
[2023-02-14T22:30:37.145-0300] {processor.py:153} INFO - Started process (PID=13873) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:37.149-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:30:37.150-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:37.149-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:37.475-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:37.474-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_imgt.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_imgt.py", line 7, in <module>
    from scripts.imgt import download
  File "/home/kallox/respaldo/thesis/dags/scripts/imgt.py", line 6, in <module>
    from helpers.requests import request_with_retry
ModuleNotFoundError: No module named 'helpers'
[2023-02-14T22:30:37.475-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:30:37.494-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_imgt.py took 0.352 seconds
[2023-02-14T22:31:07.553-0300] {processor.py:153} INFO - Started process (PID=13982) to work on /home/kallox/respaldo/thesis/dags/download_imgt.py
[2023-02-14T22:31:07.562-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_imgt.py for tasks to queue
[2023-02-14T22:31:07.562-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:31:07.562-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_imgt.py
