[2023-02-14T21:50:53.691-0300] {processor.py:153} INFO - Started process (PID=4834) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:50:53.692-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:50:53.693-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.692-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:50:53.798-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:50:53.797-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:50:53.798-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:50:53.821-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.133 seconds
[2023-02-14T21:51:24.103-0300] {processor.py:153} INFO - Started process (PID=4996) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:24.103-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:51:24.104-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:24.104-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:24.206-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:24.206-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:51:24.206-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:24.312-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.211 seconds
[2023-02-14T21:51:55.105-0300] {processor.py:153} INFO - Started process (PID=5101) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:55.106-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:51:55.106-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:55.106-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:55.290-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:51:55.289-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:51:55.290-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:51:55.314-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.210 seconds
[2023-02-14T21:52:26.151-0300] {processor.py:153} INFO - Started process (PID=5224) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:26.152-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:52:26.153-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:26.153-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:26.343-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:26.342-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:52:26.343-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:26.368-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.219 seconds
[2023-02-14T21:52:56.960-0300] {processor.py:153} INFO - Started process (PID=5330) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:56.960-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:52:56.961-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:56.961-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:57.153-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:52:57.153-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:52:57.153-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:52:57.176-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.217 seconds
[2023-02-14T21:53:23.417-0300] {processor.py:153} INFO - Started process (PID=5595) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:23.418-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:53:23.418-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:23.418-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:23.520-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:23.520-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:53:23.520-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:23.543-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.128 seconds
[2023-02-14T21:53:53.716-0300] {processor.py:153} INFO - Started process (PID=5686) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:53.717-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:53:53.718-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.718-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:53.840-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:53:53.840-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:53:53.841-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:53:53.862-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.148 seconds
[2023-02-14T21:54:24.465-0300] {processor.py:153} INFO - Started process (PID=5800) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:24.465-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:54:24.465-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:24.465-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:24.658-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:24.658-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:54:24.659-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:24.681-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.219 seconds
[2023-02-14T21:54:56.573-0300] {processor.py:153} INFO - Started process (PID=6128) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:56.574-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:54:56.574-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.574-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:56.700-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:54:56.699-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:54:56.700-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:54:56.721-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.149 seconds
[2023-02-14T21:55:26.969-0300] {processor.py:153} INFO - Started process (PID=6235) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:26.970-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:55:26.970-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:26.970-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:27.072-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:27.072-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:55:27.073-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:27.093-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.125 seconds
[2023-02-14T21:55:57.916-0300] {processor.py:153} INFO - Started process (PID=6337) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:57.916-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:55:57.917-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:57.916-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:58.114-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:55:58.113-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:55:58.114-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:55:58.138-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.224 seconds
[2023-02-14T21:56:28.915-0300] {processor.py:153} INFO - Started process (PID=6437) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:56:28.916-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:56:28.916-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:28.916-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:56:29.104-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:29.103-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:56:29.104-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:56:29.127-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.214 seconds
[2023-02-14T21:56:59.975-0300] {processor.py:153} INFO - Started process (PID=6539) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:56:59.976-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:56:59.976-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:56:59.976-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:57:00.172-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:00.171-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:57:00.172-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:57:00.197-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.225 seconds
[2023-02-14T21:57:30.745-0300] {processor.py:153} INFO - Started process (PID=6642) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:57:30.746-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:57:30.746-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:30.746-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:57:30.854-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:57:30.854-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:57:30.855-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:57:30.878-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.134 seconds
[2023-02-14T21:58:01.130-0300] {processor.py:153} INFO - Started process (PID=6746) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:01.130-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:58:01.131-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:01.131-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:01.232-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:01.232-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:58:01.233-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:01.248-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.120 seconds
[2023-02-14T21:58:31.807-0300] {processor.py:153} INFO - Started process (PID=6852) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:31.808-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:58:31.808-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.808-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:31.918-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:58:31.918-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:58:31.919-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:58:32.023-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.218 seconds
[2023-02-14T21:59:02.953-0300] {processor.py:153} INFO - Started process (PID=6956) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:02.954-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:59:02.954-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:02.954-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:03.146-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:03.146-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:59:03.147-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:03.170-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.218 seconds
[2023-02-14T21:59:33.944-0300] {processor.py:153} INFO - Started process (PID=7062) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:33.944-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T21:59:33.945-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:33.945-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:34.135-0300] {logging_mixin.py:137} INFO - [2023-02-14T21:59:34.134-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T21:59:34.135-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T21:59:34.157-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.214 seconds
[2023-02-14T22:01:58.856-0300] {processor.py:153} INFO - Started process (PID=7419) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:01:58.857-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:01:58.857-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.857-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:01:58.969-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:01:58.968-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:01:58.969-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:01:58.986-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.132 seconds
[2023-02-14T22:02:30.153-0300] {processor.py:153} INFO - Started process (PID=7589) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:30.154-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:02:30.154-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:30.154-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:30.256-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:30.256-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:02:30.256-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:30.273-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.121 seconds
[2023-02-14T22:02:36.305-0300] {processor.py:153} INFO - Started process (PID=7804) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:36.305-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:02:36.306-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:36.305-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:36.408-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:02:36.408-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:02:36.409-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:02:36.424-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.121 seconds
[2023-02-14T22:03:07.701-0300] {processor.py:153} INFO - Started process (PID=7896) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:07.702-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:03:07.702-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:07.702-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:07.825-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:07.825-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:03:07.826-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:07.847-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.148 seconds
[2023-02-14T22:03:38.365-0300] {processor.py:153} INFO - Started process (PID=7989) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:38.366-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:03:38.366-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:38.366-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:38.568-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:03:38.567-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:03:38.568-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:03:38.583-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.220 seconds
[2023-02-14T22:04:09.296-0300] {processor.py:153} INFO - Started process (PID=8086) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:09.297-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:04:09.297-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:09.297-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:09.485-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:09.485-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:04:09.485-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:09.508-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.214 seconds
[2023-02-14T22:04:40.381-0300] {processor.py:153} INFO - Started process (PID=8178) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:40.382-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:04:40.382-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:40.382-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:40.569-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:04:40.568-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:04:40.569-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:04:40.592-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.213 seconds
[2023-02-14T22:05:11.019-0300] {processor.py:153} INFO - Started process (PID=8272) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:11.020-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:05:11.020-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:11.020-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:11.145-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:11.144-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:05:11.145-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:11.168-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.152 seconds
[2023-02-14T22:05:41.525-0300] {processor.py:153} INFO - Started process (PID=8364) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:41.526-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:05:41.527-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:41.527-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:41.648-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:05:41.647-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:05:41.648-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:05:41.668-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.145 seconds
[2023-02-14T22:06:12.468-0300] {processor.py:153} INFO - Started process (PID=8460) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:12.469-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:06:12.469-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:12.469-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:12.570-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:12.570-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:06:12.571-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:12.676-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.210 seconds
[2023-02-14T22:06:43.492-0300] {processor.py:153} INFO - Started process (PID=8583) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:43.493-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:06:43.493-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:43.493-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:43.680-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:06:43.680-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:06:43.680-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:06:43.704-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.214 seconds
[2023-02-14T22:07:17.192-0300] {processor.py:153} INFO - Started process (PID=8851) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:17.192-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:07:17.192-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:17.192-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:17.292-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:17.292-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:07:17.292-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:17.312-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.122 seconds
[2023-02-14T22:07:48.573-0300] {processor.py:153} INFO - Started process (PID=8944) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:48.574-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:07:48.574-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:48.574-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:48.698-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:07:48.697-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:07:48.698-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:07:48.719-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.148 seconds
[2023-02-14T22:08:19.414-0300] {processor.py:153} INFO - Started process (PID=9041) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:19.415-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:08:19.415-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:19.415-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:19.597-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:19.596-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:08:19.597-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:19.614-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.201 seconds
[2023-02-14T22:08:50.500-0300] {processor.py:153} INFO - Started process (PID=9132) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:50.500-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:08:50.501-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:50.501-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:50.715-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:08:50.715-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:08:50.715-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:08:50.732-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.234 seconds
[2023-02-14T22:09:21.332-0300] {processor.py:153} INFO - Started process (PID=9223) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:21.333-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:09:21.334-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:21.334-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:21.578-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:21.577-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:09:21.578-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:21.606-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.276 seconds
[2023-02-14T22:09:52.095-0300] {processor.py:153} INFO - Started process (PID=9315) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:52.096-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:09:52.097-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:52.097-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:52.224-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:09:52.223-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:09:52.224-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:09:52.245-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.153 seconds
[2023-02-14T22:10:22.514-0300] {processor.py:153} INFO - Started process (PID=9411) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:22.515-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:10:22.516-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:22.516-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:22.637-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:22.636-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:10:22.637-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:22.657-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.145 seconds
[2023-02-14T22:10:53.196-0300] {processor.py:153} INFO - Started process (PID=9535) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:53.197-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:10:53.197-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:53.197-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:53.298-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:10:53.298-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:10:53.299-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:10:53.412-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.218 seconds
[2023-02-14T22:11:24.319-0300] {processor.py:153} INFO - Started process (PID=9635) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:24.319-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:11:24.320-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:24.319-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:24.514-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:24.513-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:11:24.514-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:24.536-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.220 seconds
[2023-02-14T22:11:55.350-0300] {processor.py:153} INFO - Started process (PID=9744) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:55.350-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:11:55.351-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:55.351-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:55.536-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:11:55.535-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:11:55.536-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:11:55.551-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.204 seconds
[2023-02-14T22:12:25.712-0300] {processor.py:153} INFO - Started process (PID=9847) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:25.713-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:12:25.713-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:25.713-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:25.836-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:25.835-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:12:25.836-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:25.857-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.147 seconds
[2023-02-14T22:12:56.058-0300] {processor.py:153} INFO - Started process (PID=9947) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:56.058-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:12:56.059-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:56.059-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:56.162-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:12:56.162-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:12:56.162-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:12:56.178-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.122 seconds
[2023-02-14T22:13:26.788-0300] {processor.py:153} INFO - Started process (PID=10279) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:26.789-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:13:26.789-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:26.789-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:27.050-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:27.049-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:13:27.050-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:27.066-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.281 seconds
[2023-02-14T22:13:57.544-0300] {processor.py:153} INFO - Started process (PID=10377) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:57.545-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:13:57.545-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:57.545-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:57.736-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:13:57.736-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:13:57.737-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:13:57.763-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.221 seconds
[2023-02-14T22:14:28.170-0300] {processor.py:153} INFO - Started process (PID=10468) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:28.170-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:14:28.170-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:28.170-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:28.366-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:28.366-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:14:28.366-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:28.382-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.214 seconds
[2023-02-14T22:14:58.546-0300] {processor.py:153} INFO - Started process (PID=10560) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:58.547-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:14:58.547-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:58.547-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:58.739-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:14:58.738-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:14:58.739-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:14:58.755-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.211 seconds
[2023-02-14T22:15:29.220-0300] {processor.py:153} INFO - Started process (PID=10651) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:29.221-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:15:29.222-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:29.222-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:29.342-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:29.342-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:15:29.343-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:29.362-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.144 seconds
[2023-02-14T22:15:59.632-0300] {processor.py:153} INFO - Started process (PID=10746) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:59.633-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:15:59.633-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:59.633-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:59.756-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:15:59.755-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:15:59.756-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:15:59.960-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.331 seconds
[2023-02-14T22:16:30.651-0300] {processor.py:153} INFO - Started process (PID=10839) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:16:30.652-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:16:30.652-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:30.652-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:16:30.843-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:16:30.843-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:16:30.843-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:16:30.866-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.217 seconds
[2023-02-14T22:17:01.482-0300] {processor.py:153} INFO - Started process (PID=10933) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:01.483-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:17:01.484-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:01.484-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:01.707-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:01.706-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:17:01.707-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:01.723-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.244 seconds
[2023-02-14T22:17:32.060-0300] {processor.py:153} INFO - Started process (PID=11035) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:32.061-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:17:32.061-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:32.061-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:32.242-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:17:32.242-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:17:32.242-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:17:32.258-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.199 seconds
[2023-02-14T22:18:03.147-0300] {processor.py:153} INFO - Started process (PID=11127) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:03.148-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:18:03.148-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:03.148-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:03.338-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:03.338-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:18:03.338-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:03.355-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.210 seconds
[2023-02-14T22:18:33.854-0300] {processor.py:153} INFO - Started process (PID=11217) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:33.855-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:18:33.855-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.855-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:33.982-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:18:33.982-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:18:33.983-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:18:34.004-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.152 seconds
[2023-02-14T22:19:04.609-0300] {processor.py:153} INFO - Started process (PID=11310) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:04.609-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:19:04.610-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:04.610-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:04.819-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:04.818-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:19:04.819-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:04.843-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.237 seconds
[2023-02-14T22:19:35.444-0300] {processor.py:153} INFO - Started process (PID=11404) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:35.445-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:19:35.445-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:35.445-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:35.639-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:19:35.638-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:19:35.639-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:19:35.663-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.221 seconds
[2023-02-14T22:24:16.651-0300] {processor.py:153} INFO - Started process (PID=11773) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:16.652-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:24:16.653-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:16.653-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:16.791-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:16.790-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:24:16.791-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:16.813-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.166 seconds
[2023-02-14T22:24:46.983-0300] {processor.py:153} INFO - Started process (PID=11930) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:46.984-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:24:46.985-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:46.985-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:47.128-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:47.127-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:24:47.128-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:47.150-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.169 seconds
[2023-02-14T22:24:57.903-0300] {processor.py:153} INFO - Started process (PID=12188) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:57.904-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:24:57.904-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:57.904-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:58.006-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:24:58.005-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:24:58.006-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:24:58.030-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.128 seconds
[2023-02-14T22:26:11.063-0300] {processor.py:153} INFO - Started process (PID=12500) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:26:11.064-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:26:11.064-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:11.064-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:26:11.170-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:26:11.169-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:26:11.170-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:26:11.189-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.127 seconds
[2023-02-14T22:27:31.803-0300] {processor.py:153} INFO - Started process (PID=12872) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:27:31.804-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:27:31.805-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.805-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:27:31.913-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:27:31.913-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:27:31.913-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:27:31.937-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.136 seconds
[2023-02-14T22:28:02.511-0300] {processor.py:153} INFO - Started process (PID=12982) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:02.512-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:28:02.513-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:02.512-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:02.642-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:02.641-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:28:02.642-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:02.668-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.159 seconds
[2023-02-14T22:28:11.115-0300] {processor.py:153} INFO - Started process (PID=13240) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:11.116-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:28:11.116-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:11.116-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:11.239-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:11.238-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:28:11.239-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:11.257-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.144 seconds
[2023-02-14T22:28:41.562-0300] {processor.py:153} INFO - Started process (PID=13337) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:41.563-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:28:41.564-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:41.563-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:41.690-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:28:41.690-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:28:41.691-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:28:41.712-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.152 seconds
[2023-02-14T22:29:12.285-0300] {processor.py:153} INFO - Started process (PID=13436) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:12.286-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:29:12.286-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:12.286-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:12.466-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:12.466-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:29:12.467-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:12.489-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.206 seconds
[2023-02-14T22:29:43.373-0300] {processor.py:153} INFO - Started process (PID=13548) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:43.374-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:29:43.374-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:43.374-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:43.701-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:29:43.700-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:29:43.701-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:29:43.722-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.352 seconds
[2023-02-14T22:30:07.508-0300] {processor.py:153} INFO - Started process (PID=13820) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:07.509-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:30:07.509-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:07.509-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:07.611-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:07.611-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:30:07.611-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:07.635-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.128 seconds
[2023-02-14T22:30:37.891-0300] {processor.py:153} INFO - Started process (PID=13918) to work on /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:37.892-0300] {processor.py:743} INFO - Processing file /home/kallox/respaldo/thesis/dags/download_intact.py for tasks to queue
[2023-02-14T22:30:37.892-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:37.892-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:38.023-0300] {logging_mixin.py:137} INFO - [2023-02-14T22:30:38.022-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/respaldo/thesis/dags/download_intact.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/respaldo/thesis/dags/download_intact.py", line 7, in <module>
    from scripts.intact.download import download
ModuleNotFoundError: No module named 'scripts.intact.download'; 'scripts.intact' is not a package
[2023-02-14T22:30:38.023-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/respaldo/thesis/dags/download_intact.py
[2023-02-14T22:30:38.044-0300] {processor.py:175} INFO - Processing /home/kallox/respaldo/thesis/dags/download_intact.py took 0.156 seconds
