[2023-01-01T21:01:01.415-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.download_files manual__2023-01-02T00:00:56.572641+00:00 [queued]>
[2023-01-01T21:01:01.428-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.download_files manual__2023-01-02T00:00:56.572641+00:00 [queued]>
[2023-01-01T21:01:01.428-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:01:01.428-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T21:01:01.429-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:01:01.450-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): string.download_files> on 2023-01-02 00:00:56.572641+00:00
[2023-01-01T21:01:01.454-0300] {standard_task_runner.py:55} INFO - Started process 11780 to run task
[2023-01-01T21:01:01.457-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'string.download_files', 'manual__2023-01-02T00:00:56.572641+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmpz9j_ijze']
[2023-01-01T21:01:01.458-0300] {standard_task_runner.py:83} INFO - Job 172: Subtask string.download_files
[2023-01-01T21:01:01.527-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.string.download_files manual__2023-01-02T00:00:56.572641+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T21:01:01.607-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=string.download_files
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:56.572641+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T00:00:56.572641+00:00
[2023-01-01T21:01:03.751-0300] {logging_mixin.py:137} INFO - 0
[2023-01-01T21:01:04.824-0300] {logging_mixin.py:137} INFO - 1
[2023-01-01T21:02:04.883-0300] {logging_mixin.py:137} INFO - 2 inicia descanso
[2023-01-01T21:02:07.070-0300] {logging_mixin.py:137} INFO - 2
[2023-01-01T21:02:08.239-0300] {logging_mixin.py:137} INFO - 3
[2023-01-01T21:02:22.808-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-01-01T21:02:22.822-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11780. PIDs of all processes in the group: [11780]
[2023-01-01T21:02:22.823-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11780
[2023-01-01T21:02:22.823-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T21:02:22.842-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/intact/download.py", line 30, in download
    time.sleep(request_interval)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-01T21:02:22.848-0300] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=get_interactions, task_id=string.download_files, execution_date=20230102T000056, start_date=20230102T000101, end_date=20230102T000222
[2023-01-01T21:02:22.869-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 172 for task string.download_files (Task received SIGTERM signal; 11780)
[2023-01-01T21:02:22.915-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=11780, status='terminated', exitcode=1, started='21:01:00') (11780) terminated with exit code 1
