[2023-01-01T20:30:46.350-0300] {processor.py:153} INFO - Started process (PID=3599) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:30:46.351-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:30:46.351-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:30:46.351-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:30:46.358-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:30:46.357-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:30:46.358-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:30:46.377-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.029 seconds
[2023-01-01T20:31:17.482-0300] {processor.py:153} INFO - Started process (PID=4861) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:17.483-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:31:17.484-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:17.483-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:17.494-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:17.493-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:31:17.494-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:17.524-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.045 seconds
[2023-01-01T20:31:48.361-0300] {processor.py:153} INFO - Started process (PID=5243) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:48.361-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:31:48.362-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:48.362-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:48.369-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:31:48.369-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:31:48.370-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:31:48.393-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.035 seconds
[2023-01-01T20:32:18.750-0300] {processor.py:153} INFO - Started process (PID=5605) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:18.750-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:32:18.751-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:18.751-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:18.758-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:18.758-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:32:18.759-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:18.779-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:32:50.365-0300] {processor.py:153} INFO - Started process (PID=5920) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:50.365-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:32:50.366-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:50.366-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:50.372-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:32:50.372-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:32:50.373-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:32:50.393-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.031 seconds
[2023-01-01T20:33:21.219-0300] {processor.py:153} INFO - Started process (PID=6222) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:33:21.220-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:33:21.221-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:33:21.220-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:33:21.229-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:33:21.228-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:33:21.229-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:33:21.256-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.040 seconds
[2023-01-01T20:34:49.084-0300] {processor.py:153} INFO - Started process (PID=7056) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:34:49.085-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:34:49.085-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:34:49.085-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:34:49.092-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:34:49.091-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:34:49.092-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:34:49.112-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:35:20.663-0300] {processor.py:153} INFO - Started process (PID=7146) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:20.664-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:35:20.664-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:35:20.664-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:20.671-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:35:20.671-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:35:20.672-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:20.691-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:35:51.177-0300] {processor.py:153} INFO - Started process (PID=7225) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:51.178-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:35:51.178-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:35:51.178-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:51.185-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:35:51.184-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:35:51.185-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:35:51.204-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.028 seconds
[2023-01-01T20:36:21.766-0300] {processor.py:153} INFO - Started process (PID=7300) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:21.767-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:36:21.768-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:36:21.768-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:21.777-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:36:21.776-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:36:21.777-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:21.802-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.038 seconds
[2023-01-01T20:36:52.339-0300] {processor.py:153} INFO - Started process (PID=7376) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:52.340-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:36:52.341-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:36:52.341-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:52.349-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:36:52.348-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:36:52.349-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:36:52.368-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.031 seconds
[2023-01-01T20:37:23.139-0300] {processor.py:153} INFO - Started process (PID=7464) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:23.140-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:37:23.141-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:37:23.140-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:23.147-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:37:23.147-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:37:23.148-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:23.173-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.036 seconds
[2023-01-01T20:37:53.898-0300] {processor.py:153} INFO - Started process (PID=7537) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:53.899-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:37:53.900-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:37:53.900-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:53.907-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:37:53.906-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:37:53.907-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:37:53.927-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.031 seconds
[2023-01-01T20:38:24.608-0300] {processor.py:153} INFO - Started process (PID=7616) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:24.609-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:38:24.609-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:38:24.609-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:24.617-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:38:24.617-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:38:24.618-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:24.641-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.036 seconds
[2023-01-01T20:38:55.267-0300] {processor.py:153} INFO - Started process (PID=7702) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:55.267-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:38:55.268-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:38:55.268-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:55.277-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:38:55.276-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:38:55.277-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:38:55.297-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:39:25.802-0300] {processor.py:153} INFO - Started process (PID=7774) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:25.803-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:39:25.803-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:39:25.803-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:25.812-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:39:25.811-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:39:25.812-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:25.839-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.040 seconds
[2023-01-01T20:39:56.643-0300] {processor.py:153} INFO - Started process (PID=7854) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:56.644-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:39:56.644-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:39:56.644-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:56.653-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:39:56.652-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:39:56.654-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:39:56.678-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.038 seconds
[2023-01-01T20:40:27.266-0300] {processor.py:153} INFO - Started process (PID=7935) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:27.267-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:40:27.267-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:40:27.267-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:27.273-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:40:27.273-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:40:27.274-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:27.293-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.029 seconds
[2023-01-01T20:40:57.795-0300] {processor.py:153} INFO - Started process (PID=8016) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:57.795-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:40:57.796-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:40:57.796-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:57.803-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:40:57.802-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:40:57.803-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:40:57.822-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:41:28.453-0300] {processor.py:153} INFO - Started process (PID=8088) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:28.454-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:41:28.454-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:41:28.454-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:28.462-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:41:28.461-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:41:28.462-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:28.486-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.036 seconds
[2023-01-01T20:41:59.146-0300] {processor.py:153} INFO - Started process (PID=8177) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:59.147-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:41:59.148-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:41:59.148-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:59.156-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:41:59.155-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:41:59.156-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:41:59.181-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.037 seconds
[2023-01-01T20:42:29.560-0300] {processor.py:153} INFO - Started process (PID=8280) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:42:29.561-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:42:29.562-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:42:29.562-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:42:29.569-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:42:29.569-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:42:29.570-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:42:29.590-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:43:00.203-0300] {processor.py:153} INFO - Started process (PID=8356) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:00.204-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:43:00.205-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:43:00.205-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:00.213-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:43:00.212-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:43:00.213-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:00.238-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.038 seconds
[2023-01-01T20:43:30.852-0300] {processor.py:153} INFO - Started process (PID=8430) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:30.853-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:43:30.853-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:43:30.853-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:30.861-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:43:30.860-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:43:30.861-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:43:30.880-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.031 seconds
[2023-01-01T20:44:01.469-0300] {processor.py:153} INFO - Started process (PID=8519) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:01.469-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:44:01.470-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:44:01.470-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:01.476-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:44:01.475-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:44:01.476-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:01.497-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:44:32.057-0300] {processor.py:153} INFO - Started process (PID=8616) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:32.059-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:44:32.061-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:44:32.060-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:32.072-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:44:32.071-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:44:32.073-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:44:32.095-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.042 seconds
[2023-01-01T20:45:03.004-0300] {processor.py:153} INFO - Started process (PID=8711) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:03.005-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:45:03.005-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:45:03.005-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:03.012-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:45:03.011-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:45:03.012-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:03.032-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:45:34.347-0300] {processor.py:153} INFO - Started process (PID=8802) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:34.348-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:45:34.349-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:45:34.348-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:34.357-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:45:34.357-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:45:34.358-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:45:34.379-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.034 seconds
[2023-01-01T20:46:05.819-0300] {processor.py:153} INFO - Started process (PID=8891) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:05.820-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:46:05.821-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:46:05.821-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:05.828-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:46:05.827-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:46:05.828-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:05.849-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:46:37.530-0300] {processor.py:153} INFO - Started process (PID=8982) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:37.531-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:46:37.532-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:46:37.531-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:37.540-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:46:37.540-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:46:37.541-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:46:37.571-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.044 seconds
[2023-01-01T20:47:08.812-0300] {processor.py:153} INFO - Started process (PID=9063) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:08.812-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:47:08.813-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:47:08.813-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:08.818-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:47:08.818-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:47:08.819-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:08.837-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.028 seconds
[2023-01-01T20:47:39.312-0300] {processor.py:153} INFO - Started process (PID=9137) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:39.324-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:47:39.325-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:47:39.324-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:39.336-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:47:39.336-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:47:39.337-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:47:39.365-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.057 seconds
[2023-01-01T20:48:09.551-0300] {processor.py:153} INFO - Started process (PID=9205) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:09.552-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:48:09.553-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:48:09.553-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:09.561-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:48:09.560-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:48:09.561-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:09.588-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.039 seconds
[2023-01-01T20:48:40.208-0300] {processor.py:153} INFO - Started process (PID=9296) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:40.209-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:48:40.209-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:48:40.209-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:40.216-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:48:40.215-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:48:40.216-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:48:40.235-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.029 seconds
[2023-01-01T20:49:10.557-0300] {processor.py:153} INFO - Started process (PID=9373) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:10.558-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:49:10.558-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:49:10.558-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:10.566-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:49:10.565-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:49:10.566-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:10.588-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.033 seconds
[2023-01-01T20:49:41.516-0300] {processor.py:153} INFO - Started process (PID=9450) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:41.517-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:49:41.518-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:49:41.518-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:41.527-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:49:41.527-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:49:41.528-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:49:41.553-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.040 seconds
[2023-01-01T20:50:12.332-0300] {processor.py:153} INFO - Started process (PID=9532) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:12.333-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:50:12.333-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:50:12.333-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:12.341-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:50:12.341-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:50:12.342-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:12.362-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:50:42.953-0300] {processor.py:153} INFO - Started process (PID=9608) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:42.954-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:50:42.954-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:50:42.954-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:42.961-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:50:42.961-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:50:42.962-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:50:42.984-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.034 seconds
[2023-01-01T20:51:13.301-0300] {processor.py:153} INFO - Started process (PID=9687) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:13.301-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:51:13.302-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:51:13.302-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:13.308-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:51:13.308-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:51:13.309-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:13.328-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.029 seconds
[2023-01-01T20:51:44.189-0300] {processor.py:153} INFO - Started process (PID=9779) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:44.190-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:51:44.191-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:51:44.191-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:44.203-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:51:44.202-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:51:44.204-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:51:44.237-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.053 seconds
[2023-01-01T20:52:15.125-0300] {processor.py:153} INFO - Started process (PID=9858) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:15.126-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:52:15.127-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:52:15.127-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:15.137-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:52:15.136-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:52:15.138-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:15.173-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.053 seconds
[2023-01-01T20:52:45.639-0300] {processor.py:153} INFO - Started process (PID=10064) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:45.640-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:52:45.640-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:52:45.640-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:45.646-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:52:45.646-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:52:45.647-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:52:45.665-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.028 seconds
[2023-01-01T20:53:16.322-0300] {processor.py:153} INFO - Started process (PID=10216) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:16.322-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:53:16.323-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:53:16.323-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:16.329-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:53:16.329-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:53:16.329-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:16.350-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.030 seconds
[2023-01-01T20:53:47.036-0300] {processor.py:153} INFO - Started process (PID=10378) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:47.037-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:53:47.038-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:53:47.038-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:47.046-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:53:47.045-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:53:47.047-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:53:47.076-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.042 seconds
[2023-01-01T20:54:17.592-0300] {processor.py:153} INFO - Started process (PID=10509) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:17.593-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:54:17.593-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:54:17.593-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:17.600-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:54:17.599-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:54:17.600-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:17.619-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.028 seconds
[2023-01-01T20:54:50.295-0300] {processor.py:153} INFO - Started process (PID=10632) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:50.296-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:54:50.296-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:54:50.296-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:50.302-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:54:50.302-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:54:50.302-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:54:50.325-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.032 seconds
[2023-01-01T20:55:21.798-0300] {processor.py:153} INFO - Started process (PID=10756) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:21.800-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:55:21.801-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:55:21.801-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:21.813-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:55:21.812-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:55:21.814-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:21.851-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.057 seconds
[2023-01-01T20:55:52.353-0300] {processor.py:153} INFO - Started process (PID=10877) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:52.354-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:55:52.354-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:55:52.354-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:52.361-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:55:52.360-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:55:52.361-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:55:52.379-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.029 seconds
[2023-01-01T20:56:23.938-0300] {processor.py:153} INFO - Started process (PID=10959) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:23.939-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:56:23.939-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:56:23.939-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:23.946-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:56:23.946-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:56:23.946-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:23.972-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.036 seconds
[2023-01-01T20:56:54.598-0300] {processor.py:153} INFO - Started process (PID=11030) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:54.598-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:56:54.599-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:56:54.599-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:54.605-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:56:54.605-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:56:54.605-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:56:54.624-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.028 seconds
[2023-01-01T20:57:25.182-0300] {processor.py:153} INFO - Started process (PID=11103) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:25.183-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:57:25.183-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:57:25.183-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:25.191-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:57:25.191-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:57:25.192-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:25.215-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.036 seconds
[2023-01-01T20:57:55.760-0300] {processor.py:153} INFO - Started process (PID=11178) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:55.761-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:57:55.761-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:57:55.761-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:55.769-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:57:55.768-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:57:55.769-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:57:55.788-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.031 seconds
[2023-01-01T20:58:26.352-0300] {processor.py:153} INFO - Started process (PID=11252) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:26.352-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:58:26.353-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:58:26.353-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:26.361-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:58:26.360-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:58:26.361-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:26.386-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.037 seconds
[2023-01-01T20:58:57.065-0300] {processor.py:153} INFO - Started process (PID=11330) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:57.066-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:58:57.066-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:58:57.066-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:57.075-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:58:57.074-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:58:57.075-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:58:57.098-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.037 seconds
[2023-01-01T20:59:27.687-0300] {processor.py:153} INFO - Started process (PID=11406) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:27.687-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:59:27.688-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:59:27.688-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:27.696-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:59:27.695-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:59:27.697-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:27.722-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.038 seconds
[2023-01-01T20:59:58.656-0300] {processor.py:153} INFO - Started process (PID=11494) to work on /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:58.658-0300] {processor.py:743} INFO - Processing file /home/kallox/airflow/dags/download_pylgclassify.py for tasks to queue
[2023-01-01T20:59:58.659-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:59:58.659-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:58.669-0300] {logging_mixin.py:137} INFO - [2023-01-01T20:59:58.668-0300] {dagbag.py:343} ERROR - Failed to import: /home/kallox/airflow/dags/download_pylgclassify.py
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kallox/airflow/dags/download_pylgclassify.py", line 15, in <module>
    download_files = PythonOperator(task_id='download_files', python_callable=download)
NameError: name 'download' is not defined
[2023-01-01T20:59:58.669-0300] {processor.py:755} WARNING - No viable dags retrieved from /home/kallox/airflow/dags/download_pylgclassify.py
[2023-01-01T20:59:58.695-0300] {processor.py:175} INFO - Processing /home/kallox/airflow/dags/download_pylgclassify.py took 0.042 seconds
