[2023-01-23T14:28:43.674-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_antigens.iedb.drop_columns_antigens manual__2023-01-23T17:28:37.600385+00:00 [queued]>
[2023-01-23T14:28:43.688-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_antigens.iedb.drop_columns_antigens manual__2023-01-23T17:28:37.600385+00:00 [queued]>
[2023-01-23T14:28:43.689-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:28:43.689-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-23T14:28:43.689-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:28:43.710-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): iedb.drop_columns_antigens> on 2023-01-23 17:28:37.600385+00:00
[2023-01-23T14:28:43.714-0300] {standard_task_runner.py:55} INFO - Started process 5351 to run task
[2023-01-23T14:28:43.717-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_antigens', 'iedb.drop_columns_antigens', 'manual__2023-01-23T17:28:37.600385+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/get_antigens.py', '--cfg-path', '/tmp/tmp7qgbzaai']
[2023-01-23T14:28:43.718-0300] {standard_task_runner.py:83} INFO - Job 338: Subtask iedb.drop_columns_antigens
[2023-01-23T14:28:43.788-0300] {task_command.py:389} INFO - Running <TaskInstance: get_antigens.iedb.drop_columns_antigens manual__2023-01-23T17:28:37.600385+00:00 [running]> on host kallo-Ubuntu
[2023-01-23T14:28:43.866-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_antigens
AIRFLOW_CTX_TASK_ID=iedb.drop_columns_antigens
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T17:28:37.600385+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T17:28:37.600385+00:00
[2023-01-23T14:28:44.033-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/iedb/drop_columns.py", line 47, in drop_columns_antigens
    antigen = antigen.drop(columns=columns_to_drop)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/core/frame.py", line 4913, in drop
    errors=errors,
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/core/generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/core/generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['Antigen Name' 'Organism Name' 'Organism ID' '# Epitopes' '# Assays'\n '# References'] not found in axis"
[2023-01-23T14:28:44.057-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=get_antigens, task_id=iedb.drop_columns_antigens, execution_date=20230123T172837, start_date=20230123T172843, end_date=20230123T172844
[2023-01-23T14:28:44.079-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 338 for task iedb.drop_columns_antigens ("['Antigen Name' 'Organism Name' 'Organism ID' '# Epitopes' '# Assays'\n '# References'] not found in axis"; 5351)
[2023-01-23T14:28:44.088-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-23T14:28:44.121-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
