[2023-01-23T14:27:02.145-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_catnap.download_files scheduled__2023-01-21T00:00:00+00:00 [queued]>
[2023-01-23T14:27:02.158-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_catnap.download_files scheduled__2023-01-21T00:00:00+00:00 [queued]>
[2023-01-23T14:27:02.159-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:27:02.159-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-23T14:27:02.159-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:27:02.184-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): download_files> on 2023-01-21 00:00:00+00:00
[2023-01-23T14:27:02.189-0300] {standard_task_runner.py:55} INFO - Started process 4816 to run task
[2023-01-23T14:27:02.191-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_catnap', 'download_files', 'scheduled__2023-01-21T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/download_catnap.py', '--cfg-path', '/tmp/tmpudvdp1j1']
[2023-01-23T14:27:02.192-0300] {standard_task_runner.py:83} INFO - Job 334: Subtask download_files
[2023-01-23T14:27:02.264-0300] {task_command.py:389} INFO - Running <TaskInstance: download_catnap.download_files scheduled__2023-01-21T00:00:00+00:00 [running]> on host kallo-Ubuntu
[2023-01-23T14:27:02.344-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=download_catnap
AIRFLOW_CTX_TASK_ID=download_files
AIRFLOW_CTX_EXECUTION_DATE=2023-01-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-21T00:00:00+00:00
[2023-01-23T14:27:40.803-0300] {logging_mixin.py:137} INFO - Assay downloaded.
[2023-01-23T14:27:40.830-0300] {logging_mixin.py:137} INFO - Assay.tsv saved.
[2023-01-23T14:27:42.873-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-01-23T14:27:42.884-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 4816. PIDs of all processes in the group: [4816]
[2023-01-23T14:27:42.884-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 4816
[2023-01-23T14:27:42.885-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-23T14:27:42.937-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=4816, status='terminated', exitcode=0, started='14:27:01') (4816) terminated with exit code 0
