[2023-02-15T01:33:38.463-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.drop_gen_columns manual__2023-02-15T02:10:56.705877+00:00 [queued]>
[2023-02-15T01:33:38.476-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_uniprot.drop_gen_columns manual__2023-02-15T02:10:56.705877+00:00 [queued]>
[2023-02-15T01:33:38.476-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:33:38.476-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-02-15T01:33:38.476-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:33:38.488-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): drop_gen_columns> on 2023-02-15 02:10:56.705877+00:00
[2023-02-15T01:33:38.493-0300] {standard_task_runner.py:55} INFO - Started process 57556 to run task
[2023-02-15T01:33:38.495-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_uniprot', 'drop_gen_columns', 'manual__2023-02-15T02:10:56.705877+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/download_uniprot.py', '--cfg-path', '/tmp/tmp3_o0jq02']
[2023-02-15T01:33:38.496-0300] {standard_task_runner.py:83} INFO - Job 405: Subtask drop_gen_columns
[2023-02-15T01:33:38.568-0300] {task_command.py:389} INFO - Running <TaskInstance: download_uniprot.drop_gen_columns manual__2023-02-15T02:10:56.705877+00:00 [running]> on host kallo-Ubuntu
[2023-02-15T01:33:38.651-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_uniprot
AIRFLOW_CTX_TASK_ID=drop_gen_columns
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T02:10:56.705877+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T02:10:56.705877+00:00
[2023-02-15T01:33:38.652-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/respaldo/thesis/dags/scripts/uniprot.py", line 156, in drop_columns_antigen
    antigen = pd.read_csv(antigen_path)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './dags/files/uniprot/antigen.csv'
[2023-02-15T01:33:38.666-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=download_uniprot, task_id=drop_gen_columns, execution_date=20230215T021056, start_date=20230215T043338, end_date=20230215T043338
[2023-02-15T01:33:38.677-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 405 for task drop_gen_columns ([Errno 2] No such file or directory: './dags/files/uniprot/antigen.csv'; 57556)
[2023-02-15T01:33:38.707-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-15T01:33:38.734-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
