[2023-01-01T21:01:01.407-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T00:00:56.572641+00:00 [queued]>
[2023-01-01T21:01:01.421-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T00:00:56.572641+00:00 [queued]>
[2023-01-01T21:01:01.422-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:01:01.422-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T21:01:01.422-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:01:01.449-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): intact.download_files> on 2023-01-02 00:00:56.572641+00:00
[2023-01-01T21:01:01.453-0300] {standard_task_runner.py:55} INFO - Started process 11779 to run task
[2023-01-01T21:01:01.455-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'intact.download_files', 'manual__2023-01-02T00:00:56.572641+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmpc0_g_mou']
[2023-01-01T21:01:01.456-0300] {standard_task_runner.py:83} INFO - Job 171: Subtask intact.download_files
[2023-01-01T21:01:01.522-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.intact.download_files manual__2023-01-02T00:00:56.572641+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T21:01:01.595-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=intact.download_files
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:56.572641+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T00:00:56.572641+00:00
[2023-01-01T21:01:03.057-0300] {logging_mixin.py:137} INFO - 0
[2023-01-01T21:01:04.137-0300] {logging_mixin.py:137} INFO - 1
[2023-01-01T21:02:04.195-0300] {logging_mixin.py:137} INFO - 2 inicia descanso
[2023-01-01T21:02:06.653-0300] {logging_mixin.py:137} INFO - 2
[2023-01-01T21:02:07.808-0300] {logging_mixin.py:137} INFO - 3
[2023-01-01T21:02:22.808-0300] {local_task_job.py:224} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-01-01T21:02:22.823-0300] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 11779. PIDs of all processes in the group: [11779]
[2023-01-01T21:02:22.823-0300] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 11779
[2023-01-01T21:02:22.823-0300] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T21:02:22.839-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/intact/download.py", line 30, in download
    time.sleep(request_interval)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-01T21:02:22.843-0300] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=get_interactions, task_id=intact.download_files, execution_date=20230102T000056, start_date=20230102T000101, end_date=20230102T000222
[2023-01-01T21:02:22.858-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 171 for task intact.download_files (Task received SIGTERM signal; 11779)
[2023-01-01T21:02:22.875-0300] {process_utils.py:79} INFO - Process psutil.Process(pid=11779, status='terminated', exitcode=1, started='21:01:00') (11779) terminated with exit code 1
