[2022-12-20T23:17:31.324-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_iedb.drop_columns manual__2022-12-21T02:17:29.928388+00:00 [queued]>
[2022-12-20T23:17:31.340-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_iedb.drop_columns manual__2022-12-21T02:17:29.928388+00:00 [queued]>
[2022-12-20T23:17:31.340-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T23:17:31.341-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-20T23:17:31.341-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-20T23:17:31.359-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): drop_columns> on 2022-12-21 02:17:29.928388+00:00
[2022-12-20T23:17:31.364-0300] {standard_task_runner.py:55} INFO - Started process 62645 to run task
[2022-12-20T23:17:31.367-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_iedb', 'drop_columns', 'manual__2022-12-21T02:17:29.928388+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/download_iedb.py', '--cfg-path', '/tmp/tmpnwqassi0']
[2022-12-20T23:17:31.368-0300] {standard_task_runner.py:83} INFO - Job 28: Subtask drop_columns
[2022-12-20T23:17:31.459-0300] {task_command.py:389} INFO - Running <TaskInstance: download_iedb.drop_columns manual__2022-12-21T02:17:29.928388+00:00 [running]> on host kallo-Ubuntu
[2022-12-20T23:17:31.552-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_iedb
AIRFLOW_CTX_TASK_ID=drop_columns
AIRFLOW_CTX_EXECUTION_DATE=2022-12-21T02:17:29.928388+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-21T02:17:29.928388+00:00
[2022-12-20T23:17:31.553-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/iedb/drop_columns.py", line 5, in drop_first_line
    with open("./dags/files/iedb/epitope_full_v3.csv", 'r+') as fp:
FileNotFoundError: [Errno 2] No such file or directory: './dags/files/iedb/epitope_full_v3.csv'
[2022-12-20T23:17:31.567-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=download_iedb, task_id=drop_columns, execution_date=20221221T021729, start_date=20221221T021731, end_date=20221221T021731
[2022-12-20T23:17:31.579-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task drop_columns ([Errno 2] No such file or directory: './dags/files/iedb/epitope_full_v3.csv'; 62645)
[2022-12-20T23:17:31.619-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-20T23:17:31.648-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
