[2023-01-01T20:30:42.093-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_iedb.drop_columns scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-01T20:30:42.110-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: download_iedb.drop_columns scheduled__2022-12-01T00:00:00+00:00 [queued]>
[2023-01-01T20:30:42.110-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:30:42.110-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T20:30:42.110-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:30:42.124-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): drop_columns> on 2022-12-01 00:00:00+00:00
[2023-01-01T20:30:42.129-0300] {standard_task_runner.py:55} INFO - Started process 3503 to run task
[2023-01-01T20:30:42.132-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'download_iedb', 'drop_columns', 'scheduled__2022-12-01T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/download_iedb.py', '--cfg-path', '/tmp/tmpx90g3b60']
[2023-01-01T20:30:42.133-0300] {standard_task_runner.py:83} INFO - Job 149: Subtask drop_columns
[2023-01-01T20:30:42.219-0300] {task_command.py:389} INFO - Running <TaskInstance: download_iedb.drop_columns scheduled__2022-12-01T00:00:00+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T20:30:42.305-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=download_iedb
AIRFLOW_CTX_TASK_ID=drop_columns
AIRFLOW_CTX_EXECUTION_DATE=2022-12-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-01T00:00:00+00:00
[2023-01-01T20:30:42.307-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: drop_first_line() missing 1 required positional argument: 'file_path'
[2023-01-01T20:30:42.319-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=download_iedb, task_id=drop_columns, execution_date=20221201T000000, start_date=20230101T233042, end_date=20230101T233042
[2023-01-01T20:30:42.334-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 149 for task drop_columns (drop_first_line() missing 1 required positional argument: 'file_path'; 3503)
[2023-01-01T20:30:42.343-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-01T20:30:42.366-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
