[2023-01-01T21:13:21.754-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.convert_string_ids manual__2023-01-02T00:13:11.834565+00:00 [queued]>
[2023-01-01T21:13:21.768-0300] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: get_interactions.string.convert_string_ids manual__2023-01-02T00:13:11.834565+00:00 [queued]>
[2023-01-01T21:13:21.768-0300] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:13:21.768-0300] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-01T21:13:21.768-0300] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T21:13:21.789-0300] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): string.convert_string_ids> on 2023-01-02 00:13:11.834565+00:00
[2023-01-01T21:13:21.793-0300] {standard_task_runner.py:55} INFO - Started process 14403 to run task
[2023-01-01T21:13:21.796-0300] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_interactions', 'string.convert_string_ids', 'manual__2023-01-02T00:13:11.834565+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/get_interactions.py', '--cfg-path', '/tmp/tmp1epzmo5n']
[2023-01-01T21:13:21.797-0300] {standard_task_runner.py:83} INFO - Job 186: Subtask string.convert_string_ids
[2023-01-01T21:13:21.866-0300] {task_command.py:389} INFO - Running <TaskInstance: get_interactions.string.convert_string_ids manual__2023-01-02T00:13:11.834565+00:00 [running]> on host kallo-Ubuntu
[2023-01-01T21:13:21.939-0300] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kallox
AIRFLOW_CTX_DAG_ID=get_interactions
AIRFLOW_CTX_TASK_ID=string.convert_string_ids
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:13:11.834565+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T00:13:11.834565+00:00
[2023-01-01T21:13:21.944-0300] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kallox/airflow/dags/scripts/string/string_to_db.py", line 35, in string_to_db
    string_dataset = pd.read_csv(string_data_path, sep='\t', chunksize=10000000)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/kallox/anaconda3/envs/airflow/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './dags/files/string/downloads/protein_aliases.txt'
[2023-01-01T21:13:21.956-0300] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=get_interactions, task_id=string.convert_string_ids, execution_date=20230102T001311, start_date=20230102T001321, end_date=20230102T001321
[2023-01-01T21:13:21.966-0300] {standard_task_runner.py:105} ERROR - Failed to execute job 186 for task string.convert_string_ids ([Errno 2] No such file or directory: './dags/files/string/downloads/protein_aliases.txt'; 14403)
[2023-01-01T21:13:22.007-0300] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-01T21:13:22.036-0300] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
